[Server]
ServerCount=1
ServerIndex=1
ServerType=2						
IS_INTERNAL_TEST_SVR=1

[Gateway]
Ip=127.0.0.1
Port=5633

[Database]
Ip=127.0.0.1
Port=5001

[Transfer]
Ip=127.0.0.1
Port=5003

[Chat]
Ip=127.0.0.1
Port=5004

[Tong]
Ip=127.0.0.1
Port=5005

[GameServer]
Port=6666
GM=1

[Net]
LocalIP=127.0.0.1
ExternalIP=192.168.70.137

[Overload]
MaxPlayer=1500
Precision=50

[BugFix]
LiangShanNpcDebug=0

[Arbiter]
Url=http://127.0.0.1:9000
;Url=0
Log=0
